version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    # command: bundle exec rails s -b '0.0.0.0'
    # command: bundle exec puma -e development
    volumes:
      - .:/scouter
      - public-data:/scouter/public
      - tmp-data:/scouter/tmp
      - log-data:/scouter/log
    networks:
      - scouter-network
    depends_on:
      - db

  db:
    image: postgres:14.2
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: scouter_development
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - scouter-network

  web:
    build:
      context: ./nginx_docker_dev
    volumes:
      - public-data:/scouter/public
      - tmp-data:/scouter/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - scouter-network
    stdin_open: true
    tty: true

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:


networks:
  scouter-network:
    external: true
