version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production

    volumes:
      - .:/scouter
      - public-data:/scouter/public
      - tmp-data:/scouter/tmp
      - log-data:/scouter/log
    networks:
      - scouter-network

  web:
    stdin_open: true
    tty: true
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/scouter/public
      - tmp-data:/scouter/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - scouter-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:


networks:
  scouter-network:
    external: true
